// const STUDENT_INTRO_PROGRAM_ID = "HXvmw6ZPPw2BnGzaGdUErRwUtfocnvAqiuEpbSBBRThZ";
// const STUDENT_INTRO_PROGRAM_ID = "EJ6LrjwbyeQQBPewHyFFjGJdpA94MJ3z3YVrswfkF9mD";
// const STUDENT_INTRO_PROGRAM_ID = "oxc7UraX9w7BT4bcuoZsrGnoMxpYU7T8f4mbzEfkrnp";

export const STUDENT_INTRO_PROGRAM_ID =
  "26smyNoJxhRRCeYKEzgVWWz79Aref2nnxY4k8BSVWE2W";
