[features]
seeds = false
skip-lint = false
[programs.localnet]
baby_anchor = "ASLTT67FCXboVCz5bRcTGNmYQ3BkUzqVpZeRvc3azCiS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/Users/timothy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
